version: '3.8'
services:
  challenge_api:
    container_name: challenge_api_app
    image: akashi77/test-app
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
